"use client";

import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";

export default function Datenschutz() { 
  return (
    <Box className="mt-20">
      <Typography className="text-center" variant="h4" component="h1" gutterBottom>
        Datenschutz
      </Typography>
      <Container maxWidth="sm">
        <Typography variant="body2">
          Datenschutz
          Verantwortliche/r:
          HSV DOGS-Barnim 09 e.V.
          Coppistraße 11-15
          16227 Eberswalde
          Daniela Kleckers
          dani.kleckers@gmx.de
          Diese Datenschutzerklärung klärt Sie über die Art, den Umfang und Zweck der Verarbeitung von personenbezogenen Daten innerhalb dieses Onlineangebotes und der mit ihm verbundenen Webseiten, Funktionen und Inhalte (nachfolgend gemeinsam bezeichnet als „Onlineangebot“, bzw. als „Website“) auf.
          <br />1. Rechte der Nutzer
          <br />1.1 Nutzer haben das Recht, auf Antrag unentgeltlich Auskunft zu erhalten über die personenbezogenen Daten, die von dem Verantwortlichen über sie gespeichert wurden. Zusätzlich haben die Nutzer das Recht auf Berichtigung unrichtiger Daten, Einschränkung der Verarbeitung und Löschung ihrer personenbezogenen Daten, sofern zutreffend, Ihre Rechte auf Datenportabilität geltend zu machen und im Fall der Annahme einer unrechtmäßigen Datenverarbeitung, eine Beschwerde bei der zuständigen Aufsichtsbehörde einzureichen.
          <br />2. Widerspruchsrecht
          <br />2.1 Nutzer können der künftigen Verarbeitung ihrer personenbezogenen Daten entsprechend den gesetzlichen Vorgaben jederzeit widersprechen. Der Widerspruch kann insbesondere gegen die Verarbeitung für Zwecke der Direktwerbung erfolgen.
          <br />3. Änderungen der Datenschutzerklärung
          <br />3.1 Der Verantwortliche behält sich vor, die Datenschutzerklärung zu ändern, um sie an geänderte Rechtslagen, oder bei Änderungen des Dienstes sowie der Datenverarbeitung anzupassen. Sofern Einwilligungen der Nutzer erforderlich sind oder Bestandteile der Datenschutzerklärung Regelungen des Vertragsverhältnisses mit den Nutzern enthalten, erfolgen die Änderungen nur mit Zustimmung der Nutzer.
          <br />3.2 Die Nutzer werden gebeten sich regelmäßig über den Inhalt der Datenschutzerklärung zu informieren.
          <br />4. Grundsätzliche Angaben zur Datenverarbeitung und Rechtsgrundlagen
          <br />4.1 Zu den im Rahmen dieses Onlineangebotes verarbeiteten personenbezogenen Daten der Nutzer gehören Bestandsdaten (z.B., Namen und Adressen), Vertragsdaten (z.B., betreffend die in Anspruch genommene Leistungen), Nutzungsdaten (z.B., die besuchten Webseiten dieses Onlineangebotes, Interesse an dessen Inhalten), Meta-/Kommunikationsdaten (Geräte-IDs, IP-Adressen) und Inhaltsdaten (z.B., Eingaben im Kontaktformular oder Gästebuch).
          <br />4.2 Der Begriff „Nutzer“ umfasst alle Kategorien von der Datenverarbeitung betroffener Personen. Zu ihnen gehören vor allem die Besucher dieses Onlineangebotes. Die verwendeten Begrifflichkeiten, wie z.B. „Nutzer“ oder „Verantwortlicher“ sind geschlechtsneutral zu verstehen.
          <br />4.3 Der Verantwortliche verarbeitet personenbezogene Daten der Nutzer nur unter Einhaltung der einschlägigen Datenschutzbestimmungen. Das bedeutet, die Daten der Nutzer werden nur bei Vorliegen einer gesetzlichen Erlaubnis verarbeitet. D.h., insbesondere wenn die Datenverarbeitung zur Erbringung seiner vertraglichen Leistungen (z.B. Bearbeitung von Aufträgen) sowie Online-Services erforderlich, bzw. gesetzlich vorgeschrieben ist, eine Einwilligung der Nutzer vorliegt, als auch aufgrund seiner berechtigten Interessen (d.h. Interesse an der Analyse, Optimierung und (im Fall kommerzieller Nutzung) wirtschaftlichem Betrieb und Sicherheit dieses Onlineangebotes im Sinne des Art. 6 Abs. 1 lit. f. DSGVO, insbesondere bei der Reichweitenmessung, Erstellung von Profilen zu Werbe- und Marketingzwecken sowie Erhebung von Zugriffsdaten und Einsatz der Dienste von Drittanbietern.
          <br />4.4 Im Hinblick auf die Verarbeitung von personenbezogenen Daten auf Grundlage der Datenschutzverordnung (DSGVO), weist der Verantwortliche darauf hin, dass die Rechtsgrundlage der Einwilligungen Art. 6 Abs. 1 lit. a und Art. 7 DSGVO, die Rechtsgrundlage für die Verarbeitung zur Erfüllung seiner Leistungen und Durchführung vertraglicher Maßnahmen Art. 6 Abs. 1 lit. b DSGVO, die Rechtsgrundlage für die Verarbeitung zur Erfüllung seiner rechtlichen Verpflichtungen Art. 6 Abs. 1 lit. c DSGVO, und die Rechtsgrundlage für die Verarbeitung zur Wahrung seiner berechtigten Interessen Art. 6 Abs. 1 lit. f DSGVO ist.
          <br />5. Sicherheitsmaßnahmen
          <br />5.1 Der Verantwortliche trifft organisatorische, vertragliche und technische Sicherheitsmaßnahmen entsprechend dem Stand der Technik, um sicherzustellen, dass die Vorschriften der Datenschutzgesetze eingehalten werden und um damit die durch den Verantwortlichen verarbeiteten Daten gegen zufällige oder vorsätzliche Manipulationen, Verlust, Zerstörung oder gegen den Zugriff unberechtigter Personen zu schützen.
          <br />5.2 Zu den Sicherheitsmaßnahmen gehört insbesondere die verschlüsselte Übertragung von Daten zwischen Ihrem Browser und seinem Server.
          <br />6. Löschung von Daten
          <br />6.1 Die bei dem Verantwortlichen gespeicherten Daten werden gelöscht, sobald sie für ihre Zweckbestimmung nicht mehr erforderlich sind und der Löschung keine gesetzlichen Aufbewahrungspflichten entgegenstehen. Sofern die Daten der Nutzer nicht gelöscht werden, weil sie für andere und gesetzlich zulässige Zwecke erforderlich sind, wird deren Verarbeitung eingeschränkt. D.h. die Daten werden gesperrt und nicht für andere Zwecke verarbeitet. Das gilt z.B. für Daten der Nutzer, die aus handels- oder steuerrechtlichen Gründen aufbewahrt werden müssen.
          <br />7. Weitergabe von Daten an Dritte und Drittanbieter
          <br />7.1 Eine Weitergabe von Daten an Dritte (d.h. insbesondere deren Übermittlung oder Weitergabe. erfolgt nur auf Grundlage gesetzlicher Erlaubnisse und im Rahmen der gesetzlichen Vorgaben. Der Verantwortliche gibt die Daten der Nutzer an Dritte nur dann weiter, wenn dies z.B. notwendig ist, um seine vertraglichen Verpflichtungen gegenüber den Nutzern zu erfüllen oder wenn der Verantwortliche Dienstleistungen Dritter im Rahmen seiner berechtigten Interessen in Anspruch nehmen.
          <br />7.2 Sofern der Verantwortliche Dienstleistungen Dritter in Anspruch nimmt, um seine Leistungen bereitzustellen, ergreift der Verantwortliche geeignete rechtliche Vorkehrungen sowie entsprechende technische und organisatorische Maßnahmen, um für den Schutz der personenbezogenen Daten gemäß den einschlägigen gesetzlichen Vorschriften zu sorgen.
          <br />7.3 Sofern im Rahmen dieser Datenschutzerklärung Inhalte, Werkzeuge oder sonstige Mittel von anderen Anbietern (nachfolgend gemeinsam bezeichnet als „Drittanbieter“) eingesetzt werden und deren genannter Sitz sich in einem Drittland befindet, ist davon auszugehen, dass ein Datentransfer in die Sitzstaaten der Drittanbieter stattfindet. Als Drittstaaten sind Länder zu verstehen, in denen die DSGVO kein unmittelbar geltendes Recht ist, d.h. grundsätzlich Länder außerhalb der EU, bzw. des Europäischen Wirtschaftsraums. Die Übermittlung von Daten in Drittstaaten erfolgt entweder, wenn ein angemessenes Datenschutzniveau, eine Einwilligung der Nutzer oder sonst eine gesetzliche Erlaubnis vorliegt.
          <br />8. Cookies & Reichweitenmessung
          <br />8.1 Cookies sind Informationen, die von diesem Webserver oder Webservern Dritter an die Web-Browser der Nutzer übertragen und dort für einen späteren Abruf gespeichert werden. Bei Cookies kann es sich um kleine Dateien oder sonstige Arten der Informationsspeicherung handeln. Soweit in der vorliegenden Datenschutzerklärung nicht ausdrücklich angegeben, verwendet der Verantwortliche nur sogenannte „Session-Cookies“, die nur für die Zeitdauer des aktuellen Besuchs auf seinem Onlineangebot abgelegt werden (z.B. um die Speicherung Ihres Login-Status zu ermöglichen). In einem Session-Cookie wird eine zufällig erzeugte eindeutige Identifikationsnummer abgelegt, eine sogenannte Session-ID. Außerdem enthält ein Cookie die Angabe über seine Herkunft und die Speicherfrist. Diese Cookies können keine anderen Daten speichern. Session-Cookies werden gelöscht, wenn Sie die Nutzung dieses Onlineangebotes beendet haben und sich z.B. ausloggen oder den Browser schließen.
          <br />8.2 Über den Einsatz von Cookies im Rahmen pseudonymer Reichweitenmessung werden die Nutzer im Rahmen dieser Datenschutzerklärung informiert.
          <br />8.3 Falls die Nutzer nicht möchten, dass Cookies auf ihrem Rechner gespeichert werden, werden sie gebeten die entsprechende Option in den Systemeinstellungen ihres Browsers zu deaktivieren. Gespeicherte Cookies können in den Systemeinstellungen des Browsers gelöscht werden. Der Ausschluss von Cookies kann zu Funktionseinschränkungen dieses Onlineangebotes führen.
          <br />8.4 Sie können dem Einsatz von Cookies, die der Reichweitenmessung und Werbezwecken dienen, über die Deaktivierungsseite der Netzwerkwerbeinitiative (http://optout.networkadvertising.org/) und zusätzlich die US-amerikanische Webseite (http://www.aboutads.info/choices) oder die europäische Webseite (http://www.youronlinechoices.com/uk/your-ad-choices/) widersprechen.
          <br />9. Hosting
          <br />9.1 Dieses Onlineangebot wird durch die webme GmbH, Diedenhofer Strasse 8, 10405 Berlin, Deutschland (https://www.homepage-baukasten.de/) gehostet. Die Datenschutzerklärung von webme findet sich unter der Webadresse https://www.homepage-baukasten.de/de/Datenschutzerklaerung.php.
          <br />9.2 Die Rechtsgrundlage der Verarbeitung ist Art. 6 Abs. 1 lit f. DSGVO auf Grundlage der berechtigten Interessen an der Nutzung einer Server- und Softwareinfrastruktur aus Gründen der Sicherheit und Effizienz. Die Daten der Nutzer werden von webme nur zu Zwecken der Zurverfügungstellung dieses Onlineangebotes und der Aufrechterhaltung seiner Sicherheit verarbeitet.
          <br />10. Erhebung von Zugriffsdaten
          <br />10.1 Der Verantwortliche erhebt auf Grundlage seiner berechtigten Interessen im Sinne des Art. 6 Abs. 1 lit. f. DSGVO Daten über jeden Zugriff auf den Server, auf dem sich dieser Dienst befindet (sogenannte Serverlogfiles). Zu den Zugriffsdaten gehören Name der abgerufenen Webseite, Datei, Datum und Uhrzeit des Abrufs, übertragene Datenmenge, Meldung über erfolgreichen Abruf, Browsertyp nebst Version, das Betriebssystem des Nutzers, Referrer URL (die zuvor besuchte Seite., IP-Adresse und der anfragende Provider.
          <br />10.2 Logfile-Informationen werden aus Sicherheitsgründen (z.B. zur Aufklärung von Missbrauchs- oder Betrugshandlungen) für die Dauer von maximal sieben Tagen gespeichert und danach gelöscht. Daten, deren weitere Aufbewahrung zu Beweiszwecken erforderlich ist, sind bis zur endgültigen Klärung des jeweiligen Vorfalls von der Löschung ausgenommen
          <br />11. Besondere Funktionen des Onlineangebotes
          <br />11.1 Dieses Onlineangebot wird weiterentwickelt und kann sich in der Zukunft verändern. Insbesondere können einzelne Funktionen des Onlineangebotes hinzugefügt oder entfernt werden. Die nachfolgend genannten beschriebenen Funktionen gelten daher, sofern Sie innerhalb des Onlineangebotes zur Verfügung gestellt werden (z.B., kommerzielle Nutzung, Gästebuch, Forum, Newsletter, Inhalte und Dienste von Drittanbietern).
          <br />11.2 Die Rechtsgrundlage für die Datenverarbeitung im Rahmen der Zurverfügungstellung der Funktionen ist Art. 6 Abs. 1 lit. b. DSGVO. Sofern IP-Adressen gespeichert werden, erfolgt dies gem. Art. 6 Abs. 1 lit. f. DSGVO auf Grundlage der berechtigten Interessen der Abwehr und/oder Verfolgung von möglichen unzulässigen Inhalten.
          <br />12. Verarbeitung von Daten im Rahmen der Kundenbeziehungen
          <br />12.1 Sofern dieses Onlineangebot kommerziell genutzt wird, verarbeitet der Verantwortliche Bestandsdaten (z.B., Namen und Adressen sowie Kontaktdaten von Nutzern) und Vertragsdaten (z.B., in Anspruch genommene Leistungen, Namen von Kontaktpersonen, Zahlungsinformationen) der Kunden und Interessenten zwecks Erfüllung der vertraglichen Verpflichtungen und Serviceleistungen gem. Art. 6 Abs. 1 lit. b. DSGVO.
          <br />13. Kontaktformular und Anfragen
          <br />13.1 Bei der Kontaktaufnahme mit dem Verantwortlichen (per Kontaktformular oder E-Mail) werden die Angaben des Nutzers gem. Art. 6 Abs. 1 lit. b. DSGVO zur Bearbeitung der Kontaktanfrage und deren Abwicklung verarbeitet.
          <br />14. Gästebuch
          <br />14.1 Die Einträge in Gästebüchern sind für die Öffentlichkeit sichtbar. Im Rahmen des Eintrags werden der Name des Verfassers, sofern registriert oder angegeben, die angegebene Adresse der Website des Nutzers und der Zeitpunkt des Eintrags gespeichert. Ferner wird die IP-Adresse des Verfassers gespeichert, falls die Einträge einen unzulässigen Inhalt haben sollten und die IP-Adresse der Rechtsverfolgung dienen könnte. Die IP-Adressen werden spätestens nach 14 Tagen gelöscht. Ferner behält sich der Verantwortliche vor, die Einträge auf Grundlage einer sachgerechten Abwägung zu löschen.
          <br />15. Google Analytics
          <br />15.1 Der Verantwortliche setzt auf Grundlage seiner berechtigten Interessen (d.h. Interesse an der Analyse, Optimierung und (im Fall kommerzieller Nutzung) wirtschaftlichem Betrieb dieses Onlineangebotes im Sinne des Art. 6 Abs. 1 lit. f. DSGVO) Google Analytics, einen Webanalysedienst der Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. („Google“) ein. Google verwendet Cookies. Die durch das Cookie erzeugten Informationen über Benutzung des Onlineangebotes durch die Nutzer werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert.
          <br />15.2 Google ist unter dem Privacy-Shield-Abkommen zertifiziert und bietet hierdurch eine Garantie, das europäische Datenschutzrecht einzuhalten (https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active).
          <br />15.3 Google wird diese Informationen in seinem Auftrag benutzen, um die Nutzung dieses Onlineangebotes durch die Nutzer auszuwerten, um Reports über die Aktivitäten innerhalb dieses Onlineangebotes zusammenzustellen und um weitere, mit der Nutzung dieses Onlineangebotes und der Internetnutzung verbundene Dienstleistungen, dem Verantwortlichen gegenüber zu erbringen. Dabei können aus den verarbeiteten Daten pseudonyme Nutzungsprofile der Nutzer erstellt werden.
          <br />15.4 Der Verantwortliche setzt Google Analytics nur mit aktivierter IP-Anonymisierung ein. Das bedeutet, die IP-Adresse der Nutzer wird von Google innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt.
          <br />15.5 Die von dem Browser des Nutzers übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Die Nutzer können die Speicherung der Cookies durch eine entsprechende Einstellung ihrer Browser-Software verhindern; die Nutzer können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf ihre Nutzung des Onlineangebotes bezogenen Daten an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter folgendem Link verfügbare Browser-Plugin herunterladen und installieren: http://tools.google.com/dlpage/gaoptout?hl=de.
          <br />15.6 Weitere Informationen zur Datennutzung durch Google, Einstellungs- und Widerspruchsmöglichkeiten erfahren Sie auf den Webseiten von Google: https://www.google.com/intl/de/policies/privacy/partners („Datennutzung durch Google bei Ihrer Nutzung von Websites oder Apps seiner Partner“), http://www.google.com/policies/technologies/ads („Datennutzung zu Werbezwecken“), http://www.google.de/settings/ads („Informationen verwalten, die Google verwendet, um Ihnen Werbung einzublenden“).
          <br />16. Facebook Social Plugins
          <br />16.1 Der Verantwortliche nutzen auf Grundlage seiner berechtigten Interessen (d.h. Interesse an der Analyse, Optimierung und (im Fall kommerzieller Nutzung) wirtschaftlichem Betrieb seines Onlineangebotes im Sinne des Art. 6 Abs. 1 lit. f. DSGVO) Social Plugins ("Plugins") des sozialen Netzwerkes facebook.com, welches von der Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland betrieben wird ("Facebook"). Die Plugins können Interaktionselemente oder Inhalte (z.B. Videos, Grafiken oder Textbeiträge) darstellen und sind an einem der Facebook Logos erkennbar (weißes „f“ auf blauer Kachel, den Begriffen "Like", "Gefällt mir" oder einem „Daumen hoch“-Zeichen) oder sind mit dem Zusatz "Facebook Social Plugin" gekennzeichnet. Die Liste und das Aussehen der Facebook Social Plugins kann hier eingesehen werden: https://developers.facebook.com/docs/plugins/.
          <br />16.2 Facebook ist unter dem Privacy-Shield-Abkommen zertifiziert und bietet hierdurch eine Garantie, das europäische Datenschutzrecht einzuhalten (https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&status=Active).
          <br />16.3 Wenn ein Nutzer eine Funktion dieses Onlineangebotes aufruft, die ein solches Plugin enthält, baut sein Gerät eine direkte Verbindung mit den Servern von Facebook auf. Dabei werden Daten der Nutzer betreffend den Besuch und Interessen an diesem Onlineangebot sowie verwendete Soft- und Hardware, als auch den Zeitpunkt des Besuchs und die IP-Adresse der Nutzer an Facebook übermittelt. Hierbei können aus den verarbeiteten Daten Nutzungsprofile der Nutzer erstellt und Cookies mit Profildaten der Nutzer auf deren Gerät gespeichert werden. Die von Facebook verarbeiteten Daten der Nutzer können für Marketingzwecke verwendet werden.
          <br />16.4 Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch Facebook sowie die diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz der Privatsphäre der Nutzer, können diese den Datenschutzhinweisen von Facebook entnehmen: https://www.facebook.com/about/privacy/.
          <br />16.5 Wenn ein Nutzer Facebookmitglied ist und nicht möchte, dass Facebook über dieses Onlineangebot Daten über ihn sammelt und mit seinen bei Facebook gespeicherten Mitgliedsdaten verknüpft, muss er sich vor der Nutzung dieses Onlineangebotes bei Facebook ausloggen und seine Cookies löschen. Weitere Einstellungen und Widersprüche zur Nutzung von Daten für Werbezwecke, sind innerhalb der Facebook-Profileinstellungen möglich: https://www.facebook.com/settings?tab=ads oder über die US-amerikanische Seite http://www.aboutads.info/choices/ oder die EU-Seite http://www.youronlinechoices.com/. Die Einstellungen erfolgen plattformunabhängig, d.h. sie werden für alle Geräte, wie Desktopcomputer oder mobile Geräte übernommen.
          <br />17. Einbindung von Diensten und Inhalten Dritter
          <br />17.1 Der Verantwortliche setzt innerhalb dieses Onlineangebotes auf Grundlage seiner berechtigten Interessen (d.h. Interesse an der Analyse, Optimierung und (im Fall kommerzieller Nutzung) wirtschaftlichem Betrieb dieses Onlineangebotes im Sinne des Art. 6 Abs. 1 lit. f. DSGVO) Inhalts- oder Serviceangebote von Drittanbietern ein, um deren Inhalte und Services, wie z.B. Videos oder Schriftarten einzubinden (nachfolgend einheitlich bezeichnet als “Inhalte”). Dies setzt immer voraus, dass die Drittanbieter dieser Inhalte, die IP-Adresse der Nutzer wahrnehmen, da sie ohne die IP-Adresse die Inhalte nicht an deren Browser senden könnten. Die IP-Adresse ist damit für die Darstellung dieser Inhalte erforderlich. Der Verantwortliche bemüht sich nur solche Inhalte zu verwenden, deren jeweilige Anbieter die IP-Adresse lediglich zur Auslieferung der Inhalte verwenden. Drittanbieter können ferner so genannte Pixel-Tags (unsichtbare Grafiken, auch als "Web Beacons" bezeichnet) für statistische oder Marketingzwecke verwenden. Durch die "Pixel-Tags" können Informationen, wie der Besucherverkehr auf den Seiten dieser Website ausgewertet werden. Die pseudonymen Informationen können ferner in Cookies auf dem Gerät der Nutzer gespeichert werden und unter anderem technische Informationen zum Browser und Betriebssystem, verweisende Webseiten, Besuchszeit sowie weitere Angaben zur Nutzung dieses Onlineangebotes sowie Angaben zum Standort der Nutzer enthalten, als auch mit solchen Informationen aus anderen Quellen zu Nutzerprofilen verbunden werden können.
          <br />17.2 Die nachfolgende Darstellung bietet eine Übersicht von Drittanbietern sowie ihrer Inhalte, nebst Links zu deren Datenschutzerklärungen, welche weitere Hinweise zur Verarbeitung von Daten und, z.T. bereits hier genannt, Widerspruchsmöglichkeiten (sog. Opt-Out) enthalten:
          - Videos der Plattform “YouTube” des Drittanbieters Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Datenschutzerklärung: https://www.google.com/policies/privacy/, Opt-Out: https://www.google.com/settings/ads/.
          - Landkarten des Dienstes „Google Maps“ des Drittanbieters Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Datenschutzerklärung: https://www.google.com/policies/privacy/, Opt-Out: https://www.google.com/settings/ads/.
          - Google-Recaptcha, eine sog. Captcha -Verifizierung des Drittanbieters Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Google-Recaptcha dient zur Verifizierung, ob Eingaben auf seiner Website von Menschen oder von Bots o.ä. Systemen stammen. Datenschutzerklärung: https://www.google.com/policies/privacy/, Opt-Out: https://www.google.com/settings/ads/. Weitere Datenschutzhinweise und Hinweise zum Opt-Out finden sich in den jeweiligen Google-Recaptcha-Anfragen, die für die Nutzer ausgegeben werden.
        </Typography>
      </Container>
    </Box>
  )
}