import './globals.css';
import { Inter } from 'next/font/google';
import Menu from '@/app/components/Menu';
import StickyFooter from '@/app/components/StickyFooter';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu />
        <main className='mt-20'>
          {children}
        </main>
        <StickyFooter />
      </body>
    </html>
  )
}
